- name: Add user "sysadmin" with sudo permissions
  ansible.builtin.user:
    name: sysadmin
    home: "{{ sysadmin_home_dir }}"
    password: "{{ admin_password | password_hash('sha512') }}"
    groups: sudo
    append: yes
    shell: /bin/bash
  become: true


- name: change hostname
  template:
    src: "{{ hostname_template }}"
    dest: "/etc/hostname"
  become: True

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
  become: true

- name: Config Docker
  template:
    src: "{{ docker_daemon_template }}"
    dest: "{{ docker_daemon }}"
  become: True

- name: Restart Docker service
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

- name: Network config tuning
  template:
    src: "{{ sysctl_config_template }}"
    dest: "{{ sysctl_config }}"
  become: True

- name: Reload sysctl
  shell: "sysctl -p"
  become: true

- name: Install auditd
  ansible.builtin.apt:
    name: auditd
    state: present
  become: true

- name: Backup auditd config
  ansible.builtin.copy:
    src: "{{ auditd_config }}"
    dest: "{{ auditd_config }}.bak"
    remote_src: yes
  become: true

- name: Config auditd
  template:
    src: "{{ auditd_config_template }}"
    dest: "{{ auditd_config }}"
  become: True

- name: Restart auditd service
  ansible.builtin.service:
    name: auditd
    state: restarted
  become: true
