- name: add user "Sysadmin"
  user: 
    name: sysadmin 
    home: "{{ sysadmin_home_dir }}" 
  become: True

- name: change hostname
  template:
    src: "{{ hostname_template }}"
    dest: "/etc/hostname"
  become: True

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
  become: true

- name: Config Docker
  template:
    src: "{{ docker_daemon_template }}"
    dest: "{{ docker_daemon }}"
  become: True

- name: Restart Docker service
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

- name: Network config tuning
  template:
    src: "{{ sysctl_config_template }}"
    dest: "{{ sysctl_config }}"
  become: True

- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl -p
  become: true



